{
 "title": "All Tags Board",
 "tags": [ "hipvap" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Tags",
    "query": "FCF10509.VALUE,FDI10102.VALUE,FIT10102.VALUE,FIT10209.VALUE,FIT10221.VALUE,FIT10304.VALUE,FIT10502.VALUE,FIT10509.VALUE,FIT10802.VALUE,FT11001.VALUE,LDI10505.VALUE,LIT10004.VALUE,LIT10505A.VALUE,LIT10505B.VALUE,LIT11104.VALUE,LIT11807.VALUE,LIT11809.VALUE,PDI10201.VALUE,PDI10203.VALUE,PDI10303.VALUE,PDI10405.VALUE,PDT11806.VALUE,PIT10003.VALUE,PIT10101.VALUE,PIT10201.VALUE,PIT10203.VALUE,PIT10207.VALUE,PIT10210.VALUE,PIT10303.VALUE,PIT10403.VALUE,PIT10405.VALUE,PIT10408.VALUE,PIT10501.VALUE,PIT10511.VALUE,PIT10601.VALUE,PIT10801.VALUE,PIT11002.VALUE,PIT11003.VALUE,PIT11103.VALUE,PIT11803.VALUE,TIT10202.VALUE,TIT10204.VALUE,TIT10208.VALUE,TIT10211.VALUE,TIT10220A.VALUE,TIT10220B.VALUE,TIT10220C.VALUE,TIT10401.VALUE,TIT10402.VALUE,TIT10406.VALUE,TIT10409.VALUE,TIT10420A.VALUE,TIT10420B.VALUE,TIT10420C.VALUE,TIT10420D.VALUE,TIT11102.VALUE,TIT11407.VALUE,TIT11808.VALUE,FIC10102.SP,FIC10102.PV,FIC10102.SO,FIC10102.KP,FIC10102.KI,FIC10102.KD,LIC10004.SP,LIC10004.PV,LIC10004.SO,LIC10004.KP,LIC10004.KI,LIC10004.KD,LIC10505.SP,LIC10505.PV,LIC10505.SO,LIC10505.KP,LIC10505.KI,LIC10505.KD,PIC10003.SP,PIC10003.PV,PIC10003.SO,PIC10003.KP,PIC10003.KI,PIC10003.KD,PIC10101.SP,PIC10101.PV,PIC10101.SO,PIC10101.KP,PIC10101.KI,PIC10101.KD,PIC11803.SP,PIC11803.PV,PIC11803.SO,PIC11803.KP,PIC11803.KI,PIC11803.KD,TIC10202.SP,TIC10202.PV,TIC10202.SO,TIC10202.KP,TIC10202.KI,TIC10202.KD,TIC11407.SP,TIC11407.PV,TIC11407.SO,TIC11407.KP,TIC11407.KI,TIC11407.KD,SC103VFDMAN.CVEU,PIT10003.HSDSP,LIT10004.HSDSP,LIT10004.LSDSP,PIT10101.HSDSP,PIT10101.LSDSP,LIT11807.LSDSP,TIT10208.HSDSP,PIT11803.LSDSP,TIT11808.HSDSP,LIT11809.LSDSP,PIT10501.HSDSP,PIT10511.HSDSP,PIT10601.HSDSP,PIT11103.HSDSP,LIT11104.LSDSP,PIT10801.HSDSP,PIT11003.HSDSP,PIT11002.LSDSP,LIT10505A.HSDSP,LIT10505A.LSDSP,LIT10505A.LLSDSP,LIT10505B.HSDSP,LIT10505B.LSDSP,LIT10505B.LLSDSP,MBDATA_PWR_MAIN[0],MBDATA_PWR_MAIN[1],MBDATA_PWR_MAIN[2],MBDATA_PWR_MAIN[3],MBDATA_PWR_MAIN[4],MBDATA_PWR_MAIN[5],MBDATA_PWR_MAIN[6],MBDATA_PWR_MAIN[7],MBDATA_PWR_MAIN[8],MBDATA_PWR_MAIN[9],MBDATA_PWR_MAIN[10],MBDATA_PWR_MAIN[11],MBDATA_PWR_MAIN[12],MBDATA_PWR_MAIN[13],MBDATA_PWR_MAIN[14],MBDATA_PWR_DIST[0],MBDATA_PWR_DIST[1],MBDATA_PWR_DIST[2],MBDATA_PWR_DIST[3],MBDATA_PWR_DIST[4],MBDATA_PWR_DIST[5],MBDATA_PWR_DIST[6],MBDATA_PWR_DIST[7],MBDATA_PWR_DIST[8],MBDATA_PWR_DIST[9],MBDATA_PWR_DIST[10],MBDATA_PWR_DIST[11],MBDATA_PWR_DIST[12],MBDATA_PWR_DIST[13],MBDATA_PWR_DIST[14],BMS: Burner.oPrgTime_Elapsed,BMS: LFP_Time_Remains,BMS: PostPrgTime_Remains,TC_StPt_OperX10_INT,PLC: TC_SetPt_ActiveX10_INT,PLc: TC10910_CV_ManX10_INT,PLC: TC_LtoffPosX10_INT,PLC: FiringRate_AOX10_INT,TIT10904_IC1_TempX10_INT,TIT10904_IC1_HiHiSetPtX10_INT,TIT10905_IC2_TempX10_INT,TIT10905_IC2_HiHiSetPtX10_INT,TIT10906_OC1_TempX10_INT,TIT10906_OC1_HiHiSetPtX10_INT,TIT10909_OC2_TempX10_INT,TIT10909_OC2_HiHiSetPtX10_INT,FIT10902_IC1_FlowX10_INT,FIT10902_IC1_LoLoSetPtX10_INT,FIT10903_IC2_FlowX10_INT,FIT10903_IC2_LoLoSetPtX10_INT,FIT10908_OC1_FlowX10_INT,FIT10908_OC1_LoLoSetPtX10_INT,FIT10907_OC2_FlowX10_INT,FIT10907_OC2_LoLoSetPtX10_INT,TIT10914_Stack_TempX10_INT,TIT10914_Stack_HiHiSetPtX10_INT,BY11001_FlameStrengthX10_INT,TI10007.VALUE,LIC10004.VALUE,PIC10003.VALUE,PDI10104.VALUE,PIC10101.VALUE,FIC1010.VALUE,TT10221.VALUE,TIC10202.VALUE,TT10209.VALUE,TT10304.VALUE,FI11810.VALUE,PIC11803.VALUE,PDI11806.VALUE,TI11801.VALUE,TT10502.VALUE,FQI10502.VALUE,LQI10505.VALUE,LIC10505.VALUE,PDI10512.VALUE,TI10509.VALUE,FQI10509.VALUE,TI10604.VALUE,LI10603.VALUE,PIC10601.VALUE,TI11401.VALUE,TI11405.VALUE,PI11403.VALUE,PI10803.VALUE,PI10804.VALUE,TT10802.VALUE,TIT10901,TIT10907,TIT10910,PI109113,TT11001.VALUE,PI11004.VALUE,PI11007.VALUE,PI11012.VALUE,PI11014.VALUE,TI12504.VALUE,LI12503.VALUE,TI12604.VALUE,LI12603.VALUE,LG12001.VALUE,PI12003.VALUE,ZC120.VALUE,LG12201.VALUE,ZC122.VALUE,TI12804.VALUE,LI12803.VALUE"
   }
  ]
 },
 "panels": [
  {
   "title": "All Tags Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "with ds as (\r\nSELECT tag, CREATE_TIME_SERIES(time, measure_value::double) as _ \r\nFROM $__database.$__table \r\nwhere $__timeFilter\r\ngroup by tag )\r\nselect tag, _  from ds\r\n\r\n\r\n",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  },
  {
   "title": "$Tags Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT * FROM $__database.$__table where $__timeFilter \r\nand tag = '$Tags' LIMIT 10",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  },
  {
   "title": "All Tags Descriptive Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT tag, \r\nmax(measure_value::double) as max_value, \r\nmin(measure_value::double) as min_value,\r\navg(measure_value::double) as avg_value,\r\nstddev(measure_value::double) as std\r\nFROM $__database.$__table group  by tag",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  },
  {
   "title": "$Tags Distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT  time, measure_value::double FROM $__database.$__table where tag = '$Tags'\r\nand $__timeFilter\r\n",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  }
 ]
}