{
 "title": "Hot oil Heater (H-109)",
 "tags": [ "asset" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Tags",
    "query": "TIT10901,FIT10902_IC1_FlowX10_INT,FIT10903_IC2_FlowX10_INT,FIT10907_OC2_FlowX10_INT,FIT10908_OC1_FlowX10_INT,TIT10904_IC1_TempX10_INT,TIT10905_IC2_TempX10_INT,TIT10906_OC1_TempX10_INT,TIT10907,TIT10910,PI109113,PLc: TC10910_CV_ManX10_INT,TIT10914_Stack_TempX10_INT"
   }
  ]
 },
 "panels": [
  {
   "title": "All Tags Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "with ds as (\r\nSELECT tag, CREATE_TIME_SERIES(time, measure_value::double) as _ \r\nFROM $__database.$__table \r\nwhere $__timeFilter\r\ngroup by tag )\r\nselect tag, _  from ds\r\n\r\n\r\n",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  },
  {
   "title": "$Tags Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT * FROM $__database.$__table where $__timeFilter \r\nand tag = '$Tags' LIMIT 10",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  },
  {
   "title": "All Tags Descriptive Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT tag, \r\nmax(measure_value::double) as max_value, \r\nmin(measure_value::double) as min_value,\r\navg(measure_value::double) as avg_value,\r\nstddev(measure_value::double) as std\r\nFROM $__database.$__table group  by tag",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  },
  {
   "title": "$Tags Distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT  time, measure_value::double FROM $__database.$__table where tag = '$Tags'\r\nand $__timeFilter\r\n",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  }
 ]
}