{
 "title": "HT Coefficients",
 "tags": [ "hipvap" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "All Heat Transfer Coeffcients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "with ds as (\r\nSELECT tags, CREATE_TIME_SERIES(time, measure_value::double) as _ \r\nFROM $__database.$__table \r\nwhere $__timeFilter\r\ngroup by tags )\r\nselect tags, _  from ds\r\n\r\n\r\n",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  },
  {
   "title": "OVERALL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT * FROM $__database.$__table where $__timeFilter \r\nand tags = 'OVERALL' LIMIT 10",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  },
  {
   "title": "IFSG PREHEATER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 8 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT * FROM $__database.$__table where $__timeFilter \r\nand tags = 'IFSG PREHEATER' LIMIT 10",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  },
  {
   "title": "IFSG HEATER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT * FROM $__database.$__table where $__timeFilter \r\nand tags = 'IFSG HEATER' LIMIT 10",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-timestream-test\""
    }
   ]
  }
 ]
}