{
 "title": "Timeseries_board_1",
 "tags": [ "asset" ],
 "time": { "from": "2022-03-09T06:14:16.346Z", "to": "2022-03-24T06:14:16.346Z" },
 "templating": {
  "list": [
   {
    "name": "Tags",
    "query": "SELECT DISTINCT tags FROM \"hipvap-timestreamdb\".\"hipvap-pi-data-table\""
   }
  ]
 },
 "panels": [
  {
   "title": "All Tags Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "with ds as (\r\nSELECT tags, CREATE_TIME_SERIES(time, measure_value::double) as _ \r\nFROM $__database.$__table \r\nwhere $__timeFilter\r\ngroup by tags )\r\nSELECT tags, _  from ds where tags in(${asset_tags})",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-pi-data-table\""
    }
   ]
  },
  {
   "title": "$Tags Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT time, measure_value::double FROM $__database.$__table where $__timeFilter \r\nand tags = trim(split(${Tags:singlequote},'-')[1])",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-pi-data-table\""
    }
   ]
  },
  {
   "title": "All Tags Descriptive Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT tags, \r\nmax(measure_value::double) as max_value, \r\nmin(measure_value::double) as min_value,\r\navg(measure_value::double) as avg_value,\r\nstddev(measure_value::double) as std\r\nFROM $__database.$__table where tags in(${asset_tags}) and $__timeFilter group  by tags",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-pi-data-table\""
    }
   ]
  },
  {
   "title": "$Tags Distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT  time, measure_value::double FROM $__database.$__table where tags = trim(split(${Tags:singlequote},'-')[1])\r\nand $__timeFilter\r\n",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-pi-data-table\""
    }
   ]
  }
 ]
}