{
 "title": "Timeseries_board_1",
 "time": { "from": "2022-03-03T10:39:08.911Z", "to": "2022-03-03T15:41:21.019Z" },
 "templating": {
  "list": [
   { "name": "Tags", "query": "tag1, tag2" }
  ]
 },
 "panels": [
  {
   "title": "Group by tags Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT  time, measure_value::double FROM $__database.$__table \r\nwhere $__timeFilter\r\ngroup by time, tag, measure_value::double LIMIT 10 ",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-pi-data-table\""
    }
   ]
  },
  {
   "title": "$Tags Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT * FROM $__database.$__table \r\nwhere $__timeFilter AND tag = $Tags \r\nLIMIT 10 ",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-pi-data-table\""
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT  time, measure_value::double FROM $__database.$__table \r\nwhere $__timeFilter\r\ngroup by time, tag, measure_value::double LIMIT 10 ",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-pi-data-table\""
    }
   ]
  },
  {
   "title": "$Tags Distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT  time, measure_value::double FROM $__database.$__table where tag=$Tags\r\nand $__timeFilter\r\nLIMIT 10 ",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-pi-data-table\""
    }
   ]
  },
  { "title": "Data Quality/Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Data Tabel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "database": "\"hipvap-timestreamdb\"",
     "decimalSeparator": ".",
     "delimiter": ",",
     "measure": "value",
     "rawQuery": "SELECT * FROM $__database.$__table where $__timeFilter LIMIT 10",
     "schema": [
      { "name": "", "type": "string" }
     ],
     "table": "\"hipvap-pi-data-table\""
    }
   ]
  }
 ]
}